name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment only for pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables and write config.js
        run: |
          echo "window.env = { APIURL: '${{ secrets.APIURL }}', APIKEY: '${{ secrets.APIKEY }}' };" > config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: gh-pages
          folder: .  # Assuming your content is already in the root
          token: ${{ secrets.GH_TOKEN }}
